FROM nvidia/cudagl:11.3.0-devel-ubuntu20.04

WORKDIR /workspace
ENV DEBIAN_FRONTEND=noninteractive

COPY requirements.txt requirements.txt

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#     libpython3.8 \
#     python3-pip \
#     git

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        cmake \
        curl \
        gcc-8 \
        g++-8 \
        wget \
        bzip2 \
        git \
        vim \
        tmux \
        git \
        unzip \
        build-essential \
        vulkan-utils \
        mesa-common-dev \
        mesa-vulkan-drivers \
        libosmesa6-dev \
        libgl1-mesa-glx \
        libglfw3 \
        patchelf \
        libglu1-mesa \
        libxext6 \
        graphviz \
        libxtst6 \
        libxrender1 \
        libxi6 \
        libegl1 \
        libxrandr-dev \
        libxinerama-dev \
        libxcursor-dev \
        mpich \
        ninja-build

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN rm /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0 /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0.0.0 /usr/share/glvnd/egl_vendor.d/50_mesa.json

RUN curl -o ~/miniconda.sh -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh

ENV PATH /opt/conda/bin:$PATH

RUN conda create -n emm python=3.8 -y

RUN /opt/conda/envs/emm/bin/pip install -r requirements.txt
RUN /opt/conda/envs/emm/bin/pip install --upgrade setuptools
RUN /opt/conda/envs/emm/bin/pip install -e "git+https://github.com/allenai/allenact.git@callbacks#egg=allenact&subdirectory=allenact"
RUN /opt/conda/envs/emm/bin/pip install -e "git+https://github.com/allenai/allenact.git@callbacks#egg=allenact_plugins[ai2thor]&subdirectory=allenact_plugins"
RUN /opt/conda/envs/emm/bin/pip install git+https://github.com/openai/CLIP.git@3b473b0e682c091a9e53623eebc1ca1657385717
RUN /opt/conda/envs/emm/bin/pip install -U ai2thor

ENV NVIDIA_DRIVER_CAPABILITIES=graphics,utility,compute,display

COPY nvidia_icd.json /usr/share/vulkan/icd.d/nvidia_icd.json
COPY nvidia_layers.json /usr/share/vulkan/implicit_layer.d/nvidia_layers.json